export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'
export const CREATE_business = 'CREATE_business'
export const FETCH_business = 'FETCH_business'
export const FETCH_businessES = 'FETCH_businessES'
export const EDIT_business = 'EDIT_business'
export const DELETE_business = 'DELETE_business'